image: gcc
pages:
  stage: deploy
  before_script:
  - apk --update-cache add brotli git zip gcc musl-dev binutils binutils-gold
  script:
  - src/make-dist.sh .public
  - find .public -type f -exec gzip -9 -f -k {} +
  - find .public -type f -exec brotli -f -k {} +
  - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
