image: alpine:latest
pages:
  stage: deploy
  before_script:
  - apk --update-cache add brotli git zip gcc musl-dev binutils binutils-gold
  script:
  - src/make-dist.sh .public
  - find .public -type f | while read f; do gzip -9 -f -k "$f"; brotli -f -k "$f"; done
  - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
