image: alpine:latest
pages:
  stage: deploy
  before_script:
  - apk update && apk add brotli git
  script:
  - mkdir -p .public
  - git ls-files | grep -E '\.(html?|js|css)$' | xargs tar -c | tar -xC .public
  - find .public -type f -exec gzip -9 -f -k {} +
  - find .public -type f -exec brotli -f -k {} +
  - mv .public public
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - master
